theme = "catppuccin_latte_transparent"
#theme = "boo_berry"

[editor]
# Highlight all lines with a cursor
cursorline = true
# Use relative line numbers
line-number = "relative"
# Show a ruler at column 120
rulers = [120]
# Force the theme to show colors
true-color = true
# Use ctrl-x for completion
auto-completion = false
popup-border = "all"
# Minimum severity to show a diagnostic after the end of a line
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error" # Show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
enable = true
# Disable automatically popups of signature parameter help
auto-signature-help = false
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
C-p = "signature_help"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"
home = "goto_first_nonwhitespace"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-p = "signature_help"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"
home = "goto_first_nonwhitespace"
A-x = "extend_to_line_bounds"
X = "select_line_above"
'A-,' = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

[keys.select]
C-right = "move_next_word_start"
C-left = "move_prev_word_start"
home = "goto_first_nonwhitespace"
A-x = "extend_to_line_bounds"
X = "select_line_above"
