backlight:
{
    # restore_on_exit = true;
    trans_fixed = 800;          # smooth transition of 800ms
    shutter_threshold = 0.10;   # discard captures with covered webcam

    # timeouts in seconds: [ day, night, event ] on AC
    ac_timeouts = [ 600, 2700, 300 ];
};
