inhibit:
{
    # Inhibit dimmer/DPMS when an inhibition hint is received
    # (e.g. fullscreen video, presentation mode).
    # disabled = true;

    # Also inhibit when screensaver is active
    # inhibit_docked = false;

    # Inhibit during screensaver
    # inhibit_screensaver = true;
};
