keyboard:
{
    ## disabled = true;

    # Ambient brightness -> keyboard backlight curves
    # ac_regression_points   = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ];
    # batt_regression_points = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ];
};
