screen:
{
    ## disabled = true;

    # Timeouts between screen compensation recalibrations: [ AC (s), battery (s), event (s) ]
    # ac_timeouts   = [ 30, 15, 10 ];
    # batt_timeouts = [ 60, 30, 15 ];
};
