general {
    lock_cmd = ~/.config/gtklock/lock.sh
    before_sleep_cmd = ~/.config/gtklock/lock.sh
    after_sleep_cmd = ~/nixos-config/bin/resume-actions.sh
}

# Notification 30 sec avant verrouillage
listener {
    timeout = 570
    on-timeout = notify-send -u critical -t 25000 -i ~/.config/waybar/caution_4539472.png "🔒 Verrouillage imminent" "L'écran se verrouillera dans 30 secondes"
    on-resume = swaync-client -C
}

# Verrouillage à 10 min
listener {
    timeout = 600
    on-timeout = ~/.config/gtklock/lock.sh
}

# Suspend à 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
