general {
    lock_cmd = ~/.config/gtklock/lock.sh
    unlock_cmd = ~/nixos-config/bin/theme-auto-switch.sh
    before_sleep_cmd = ~/.config/gtklock/lock.sh &
    after_sleep_cmd = ~/nixos-config/bin/resume-actions.sh
}

# Notification 30 sec before lock
listener {
    timeout = 570
    on-timeout = notify-send -u critical -t 25000 -i ~/.config/waybar/caution_4539472.png "🔒 Verrouillage imminent" "L'écran se verrouillera dans 30 secondes"
    on-resume = swaync-client -C
}

# Turn off screen after 2 min when locked
listener {
    timeout = 120
    on-timeout = pgrep gtklock > /dev/null && niri msg action power-off-monitors
    ignore_inhibit = true
}

# Lock at 10 min
listener {
    timeout = 600
    on-timeout = ~/.config/gtklock/lock.sh
}

# Turn off screen 2 min after auto-lock (600 + 120)
listener {
    timeout = 720
    on-timeout = niri msg action power-off-monitors
    ignore_inhibit = true
}

# Suspend at 15 min
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
