[[snippet]]
name = "for"
prefix = "for"
body = "{% for ${1:item} in ${2:items} %}\n  $0\n{% endfor %}"
description = "Django for loop"

[[snippet]]
name = "if"
prefix = "if"
body = "{% if ${1:condition} %}\n  $0\n{% endif %}"
description = "Django if statement"

